<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbw5tdu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbw5tdu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbw5tdu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbw5tdu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXbw5tdu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xbw5tdu',
    'container.build_id' => 'b8a5a0b9',
    'container.build_time' => 1521283450,
));
